### ISSUE TITLE
Document how to update to a new batou release

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#103]
Currently I edit the `requirements.txt` file and run `./batou appenv-update-lockfile` afterwards to update `requirements.lock`.

I am not sure if this is the canonical way and I did not find anything about that topic in the documentation at https://batou.readthedocs.io/en/stable/index.html
(Additionally the neither the documentation nor `./batou -h` mentions the `appenv-update-lockfile` subcommand.)

If my approach is the correct one, I could contribute a bit of documentation.

**Comment by gforcada** [comment]
And docs on how to update from 1.x to 2.x would be extra cherries on top :cherries: :sparkles:

**Comment by icemac** [comment]
> And docs on how to update from 1.x to 2.x would be extra cherries on top 🍒 ✨

@gforcada These extra cherries have already been delivered, see https://batou.readthedocs.io/en/stable/upgrading.html

**Comment by jugmac00** [comment]
Note: you can't use the latest batou2 version when you have Python 3.9 installed, see #93 ( which makes me wonder how @icemac runs it )

**Comment by icemac** [comment]
@jugmac00 The simple answer is: none of my projects in already running on Python 3.9. See also https://pythonspeed.com/articles/switch-python-3.9/ for some interesting ideas when to switch to 3.9.

**Comment by ctheune** [comment]
The whole appenv-update-lockfile is a kind of 'hidden' gem which I'm not sure how to expose correctly. Appenv is a 'meta' layer and provides '--appenv-help'. 

Updating the requirements.txt is the way to go. If batou has specific requirements those will be embedded in the requirements and you just pin them for each environment as you go (to allow specifying your own dependencies).

**Comment by ctheune** [comment]
@icemac I'd appreciate that doc contribution :)

**Comment by icemac** [comment]
@ctheune See #105.
