### ISSUE TITLE
Travis-ci.org shuts down at the end of 2020

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#109]
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

Also, the pricing model changes, see here
https://github.com/zopefoundation/meta/issues/38

**Comment by jugmac00** [comment]
As Travis is no longer used, maybe you want to disable https://travis-ci.org/github/flyingcircusio/batou

**Comment by ctheune** [comment]
Done.
