### ISSUE TITLE
Updating a lockfile on Ubuntu is broken

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#116]
When updating the lockfile via 

```
./batou appenv-update-lockfile
```

the following entry is added into the lockfile
```
pkg-resources==0.0.0
```

The subsequent deployment then fails.

**Comment by ctheune** [comment]
I think this might be fixed now already using the separated appenv structure and the improved handling of Python version-specific dependencies.

**Comment by ctheune** [comment]
Yeah, this has been fixed with newer appenvs, but one needs to document the proper Python versions and then it will ensure the lowest version being used for updating which then causes non-yet-stdlibrary items to be pulled in as dependencies explicitly.
