### ISSUE TITLE
batou 2.2 release?

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#122]
As Python 3.9 is now final and it gets installed, so #93 is more likely to occur.
May I ask for a new batou release to get #108 into a released version?

**Comment by icemac** [comment]
CC: @ctheune

**Comment by ctheune** [comment]
yeah, i'll try to get 2.2 out of the door soon. Please use pinned VCS commits until then.

**Comment by ctheune** [comment]
I have reviewed and rescheduled open issus and am trying to release 2.2 this week.

**Comment by ctheune** [comment]
And its landet.

**Comment by icemac** [comment]
Thank you!
