### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#144]
Several times this week I experienced some deployment issues, which were quite hard to debug, as batou does not offer a verbose mode - at least I do not know of one.

Some examples from the top of my head...

1)
I experienced an error in the SSHKeyPair component because of the used ssh-keyscan could not connect to IPv6 (for 20 years) and still reported an exit code of 0, which just recently changed. see https://github.com/flyingcircusio/batou_ext/issues/37

I would have loved to see what ssh-keyscan printed to the console the last 5 years :-)

2)
batou deployment ran successful, but my Zope app did not start afterwards

The reason ... huh. When I manually ran buildout it complained about a missing version pin. After pinning that version, I ran the batou deployment again, and it worked.

I would have loved to see the buildout output during a batou deployment.

3)
I started using `pikepdf` which worked on my Ubuntu dev machine, but the deployment on Nixos failed because of a missing library on Nixos. I can' recall the error message, but it was not enough info, something like `ImportError: pikepdf's extension library failed to import` but it would have been nice to see which lib was missing.

Besides these deployment issues, sometimes a single step takes super long, e.g buildout - I'd love to see what's going on.

Or today I stared at `Waiting for remaining connections` for several minutes without knowing what is going on.

I understand, that most of the time deployement works well, and you do not want to see too much output, so I think an option to make output verbose would be the way to go.

P.S.: Thanks for all the work you put into batou making it a better dev experience!

**Comment by ctheune** [comment]
Batou has a general `--debug` switch that causes more output to show up. Would that have maybe helped already?

**Comment by jugmac00** [comment]
I was not aware of the `--debug` option, so I will certainly use it the next time I encounter problems.

I used it just now for a normal deployment, and at least I now can guess why my deployment takes so long. I read several times `Sending 41788107 bytes of changes`.

eg
```
blissstag50: Bootstrapping ...
rpc blissstag50.fcio.net: lock(*(), **{})
Sending 41788636 bytes of changes
blissstag50.fcio.net: message: ('batou-result', 'OK')
rpc blissstag50.fcio.net: ensure_repository(*('~/deployment', 'git-bundle'), **{})
blissstag50.fcio.net: message: ('batou-result', '/srv/s-bliss/deployment')
rpc blissstag50.fcio.net: ensure_base(*('.',), **{})
blissstag50.fcio.net: message: ('batou-result', '/srv/s-bliss/deployment/.')
blissstag50: Updating repository ...
rpc blissstag50.fcio.net: git_current_head(*('staging',), **{})
blissstag50.fcio.net: message: ('batou-result', None)
cmd: LANG=C LC_ALL=C LANGUAGE=C git bundle create /tmp/tmp9zbft00q staging
Sending 41788107 bytes of changes
Unbundling changes
```
even for the same vm oO

I guess we can close this issue then.

I will either try to replicate above mentioned problems and create separate issues, or I just wait until next time a problem arises.

**Comment by ctheune** [comment]
Those 41mib are quite interesting. -_-

Feel free to open up a new issue for that one ...
