### ISSUE TITLE
requirements.lock with different python versions

### ISSUE THREAD

**Issue by zagy** [flyingcircusio/batou#145]
When having python 3.9 locally but the deployment needs to run with python 3.7, too one has to add 

```
importlib-metadata
typing-extensions
```

to the requirements.txt (when using requirements.lock). Those packages are required for Python 3.7 but do not harm for 3.9.

**Comment by icemac** [comment]
https://github.com/flyingcircusio/appenv/pull/28 has to be merged first, then a PR can be created copying `appenv.py` here to fix the issue.

**Comment by icemac** [comment]
#207 Brings the fix from `appenv` to batou to fix this issue here.
