### ISSUE TITLE
document how to debug deployment problems

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#149]
A dedicated page in the docs about debugging **batou** would be nice.

So far I have these experiences...

- you can use `self.log("output")` to print something to the terminal
- you can't set a `breakpoint()` as the deployment breaks without stopping at the breakpoint
  - describe why this happens (because of threading?)
  - alternatives? (except printing to the console?)
- you can use the `-d` flag which enables debugging output during deployment
- ....

**Comment by icemac** [comment]
You can use `rpdb` to remotely debug `batou` runs. Works like a charm even though the last release of this package is a bit dated: https://pypi.org/project/rpdb/

**Comment by ctheune** [comment]
Might be a duplicate of #199
