### ISSUE TITLE
Replace GPG encryptiong with `age`

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#154]
GPG isn't really a modern solution any longer. It was easy to integrate and better than nothing, but we really should consider switching to something specific.

See https://latacora.singles/2019/07/16/the-pgp-problem.html and https://docs.google.com/document/d/11yHom20CrsuX8KQJXBBw04s80Unjv8zCg_A7sPAX_9Y/view.

Implementation: https://github.com/FiloSottile/age

Interestingly age could use SSH keys and we could integrate with github and gitlab (and maybe our directory) to assist this.

**Comment by ctheune** [comment]
We could allow adding (multiple) URLs (to the encrypted file? to the public environment file?) that provide SSH public keys and are refreshed during re-encryption (but can work with the old keys if URLs are not available right now).

In our directory we could add (secret?) public URLs that provide lists of SSH keys for users that have access to a specific RG (with a specific permission), like https://my.flyingcircus.io/rg/<identifier>/(login|sudo-srv|...).keys

We should consider whether those identifiers become readable, which helps writing them down in batou and not confusing them or whether they should become properly non-identifiable.

**Comment by ctheune** [comment]
When updating the public keys we should record them (and commit them) in a separate file. When re-encrypting we should try to update but allow for offline workflows to use the old recorded keys.

**Comment by ctheune** [comment]
Public directory API is somewhat of a confidentiality issue where an RG needs to have a token instead of a a guessable name. /rg/<rgname>/<token>/... (users|login|sudo-srv|...).pubkeys

**Comment by elikoga** [comment]
Some interesting sub problems to consider:

The nix store is world readable: 
- https://github.com/yaxitech/ragenix
- https://github.com/ryantm/agenix
- Just scan nix files for secrets

A general purpose project for doing this in git repositories (with age) exists:
- https://github.com/slok/agebox

There is also for gpg/pgp:
https://github.com/AGWA/git-crypt

**Comment by elikoga** [comment]
#264 related

**Comment by ctheune** [comment]
The current implementation looks quite good already.

Notes to do from the review:

* [ ] support creating new environments with age (use `secrets-provider = age|gpg` and default to gpg in new environments and explicitly add this line, with a comment about the possible options when creating new environments)
* [ ] support changing the secrets provider option on the fly, recode and unlink old files
* [ ] re-add the explicit cleartext file that shows which keys were used and retrieved from which locations
* [ ] documentation (incl. examples what to put in your shell rc/profile and the 1p integration)
