### ISSUE TITLE
Allow to extract password protected zip files

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#164]
It would be nice if batou.lib.archiv.Extract() could support also password protected files (if the format does support it). An actually usecase would be to extract a zip-file having a password set.

**Comment by icemac** [comment]
@ctheune This is not such an easy task:

* The currently used `unzip` program does not support all possible encryption algorithms and it expects the password to be provided via command line, this way it could appear in the output.
* The `zipfile` library in Python also does not support AES encryption and the decryption part is written in pure Python. The documentation says it is slow. Additionally it is not able to encrypt ZIP files.
* There is [pyzipper](https://pypi.org/project/pyzipper/) which supports AES but according to its documentation you have to know the compression type and encryption type beforehand (it does not automatically detect them).
* We found [pyminizip](https://pypi.org/project/pyminizip/) which at least supports encryption but someone wrote about problems with using it for decryption.

So we need a bit guidance about the use case:

* Do you want to extract arbitrary encrypted ZIP files or do you/the customer create them for the purpose to be used in batou?
* How important is the support for AES encryption?

**Comment by frlan** [comment]
The actual case I was dealing with was able to be solved with the -P option for the command line tool. Unfortunately I cannot find the zip-file anymore to check for the alg. used inside.

**Comment by ctheune** [comment]
Yeah, I'd hate to use -P. However, we could automate the commandline (pexpect or manually) but honestly I think this isn't important enough to spend hours on. @frlan I think if we keep running into password protected files (that keep changing) we need to fix this properly, otherwise I advise you to unpack and store the file in a trusted location with us.
