### ISSUE TITLE
Make batou ssh call more flexible

### ISSUE THREAD

**Issue by zagy** [flyingcircusio/batou#17]
Especially in deployment pipelines it needs to be defined in the pipeline which user and/or key should be used to connect. 

I suggest using an environment variable `BATOU_SSH_EXTRA_ARGS`

**Comment by zagy** [comment]
Or maybe BATOU_SSH_COMMAND, so it's equivalent to GIT_SSH_COMMAND.

**Comment by ctheune** [comment]
I have another option here: if you put ssh_config in the batou directory it will pick this up. How about that?

**Comment by zagy** [comment]
Would probably work as well. We actually don't require this anymore, using batou inside docker executor started by jenkins.

**Comment by ctheune** [comment]
Ok, so apparently nobody jumped on this. I'm going to reject this for now. We do have some more flexibility with the custom ssh_config file.
