### ISSUE TITLE
When adding a file to secrets all other secret files of theat environment will be re-encrypted

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#172]
Not 100% it's wrong behaviour but it adds a lot of noise to ones version control system making merges/diffs/* harder. 

When editing a file via e.g. `./batou secrets edit staging myFile` all other files for this environments gets re-encrypted:

(output from git status)
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   secrets/staging-IT-Services.crt
	modified:   secrets/staging-trust.cer
	modified:   secrets/staging-some.prv.key
	modified:   secrets/staging-some.pub.pem
	modified:   secrets/staging-secrets.json
	modified:   secrets/staging-myFile
	modified:   secrets/staging.cfg
```

**Comment by ctheune** [comment]
This is actually somewhat intentional: a) we don't have to check whether there were changes in the target list and b) this also picks up key changes (or missing keys). It's not ideal overall, but the tradeoff I'm OK with for now. Everything else is rather a discussion about getting rid of GPG.
