### ISSUE TITLE
Add pyflakes to linting setup.

### ISSUE THREAD

**Issue by sallner** [flyingcircusio/batou#192]
In the test to the secrets an undefined variable `secrets` occurred. 
https://github.com/flyingcircusio/batou/blob/638038744281c804f2ad02c95c141f48b476b8fd/src/batou/secrets/tests/test_secrets.py#L59-L65

I would propose to add `pyflakes` to the linting chain, to ensure those kind of errors do not happen. 

A run over the current codebase resulted in the following output.

```
[batou]$pyflakes src/
src/batou/deploy.py:9:1 'batou.ConfigurationError' imported but unused
src/batou/deploy.py:9:1 'batou.DeploymentError' imported but unused
src/batou/deploy.py:9:1 'batou.FileLockedError' imported but unused
src/batou/deploy.py:13:1 '.environment.MissingEnvironment' imported but unused
src/batou/remote_core.py:392:47 undefined name 'e'
src/batou/conftest.py:7:12 local variable 'FIXTURE' is assigned to but never used
src/batou/utils.py:111:25 '...'.format(...) has unused arguments at position(s): 0, 1
src/batou/fixtures.py:2:1 'subprocess' imported but unused
src/batou/secrets/encryption.py:7:1 'shlex' imported but unused
src/batou/secrets/edit.py:2:1 'glob' imported but unused
src/batou/secrets/tests/test_secrets.py:64:13 undefined name 'secrets'
src/batou/tests/test_remote.py:40:5 local variable 'd' is assigned to but never used
src/batou/tests/test_remote_core.py:111:70 local variable 'f' is assigned to but never used
src/batou/tests/test_utils.py:60:39 local variable 'f' is assigned to but never used
``

**Comment by sallner** [comment]
When working on https://github.com/flyingcircusio/batou/issues/184 I actually run into the problem with the test mentioned above. I actually encountered a `NameError` in this test now. I would like to prioritize this issue higher.

**Comment by ctheune** [comment]
I started working on this and I'm running into some interesting things about the linter setup: depending on the way we call the (now) three main tools (flake8, isort, yapf) we seem to get different results:

* from my editor
* from precommit
* from precommit when run through tox

In general I think we need to try to convince all tools to use the settings in setup.cfg.
