### ISSUE TITLE
Report durations for root-level components and individual steps

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#201]
also report verify/update timings separately in debug mode

**Comment by ctheune** [comment]
This doesn't have to go into 2.3 directly but maybe can be attached to 2.3.1.

**Comment by ctheune** [comment]
CCing @EdwardBock

**Comment by stevleibelt** [comment]
> This doesn't have to go into 2.3 directly but maybe can be attached to 2.3.1.

Are you able to estimate the amount of time and touched code this feature will take?
My gut feeling tells me, that this feature does not fit into a [patch](https://semver.org/) release version. Seen from an eagle perspective with really little knowledge about batou itself.

**Comment by elikoga** [comment]
Since it adds functionality it doesn't conceuptually fit into `patch` from SemVer. I'm not sure how tight batou follows SemVer though.
I don't believe that the amount of touched code would be significantly high though

**Comment by stevleibelt** [comment]
@elikoga thanks for your estimation. At the end, this feature could be developed and could later on be fitted in the right release schema :-).

**Comment by elikoga** [comment]
https://github.com/flyingcircusio/batou/commit/9b62b1024033139e5e819b02b59deabd08afa530#diff-acfd1706f4510ec0c2359bde2a62e4c4bc685bf88e120ac9a4866594aeb993f4R134-R136

We already have a timer for that since 2013, so we just need to report the collected data

**Comment by elikoga** [comment]
- [ ] get feedback

**Comment by elikoga** [comment]
Closed by https://github.com/flyingcircusio/batou/pull/346
