### ISSUE TITLE
Make it easier to differ between -P and real deployment

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#209]
Usually running something like that:

`./batou deploy -P staging`

before actually deploying an environment to see whether all looks ok. 

Unfortunately the output

```
xyz.example.org: Deploying component crontab ...
xyz.example.org: Deploying component nrpehost ...
xyz.example.org: Deploying component logrotate ...
============================================ DEPLOYMENT PREDICTION FINISHED ============================================
```

quiet often can be mistaken as "Deployment done and ok" as the colours and the general appearance is very similar. Maybe we should make it even more obvious that this was only a prediction, not the real deployment (adding a yellow box or something)

**Comment by ctheune** [comment]
Sounds good. Yellow is more of a success signal. I'd recommend using a blue or a purple.
