### ISSUE TITLE
Cannot install batou on Python 2.7 any more

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#25]
Creating a fresh deployment using Python 2.7 fails because `virtualenv` tries to install the newest version of `setuptools` (aka 45.1.0) which is no longer compatible with Python 2.

Trying to pin `setuptools` using `requirements.txt` did not help.

Any ideas how to solve this issue?

**Comment by zagy** [comment]
This is probably a virtualenv installed in python3, which isn't required there (`python3 -m venv`)

But we should requires setuptools<45 in batou 1.x

**Comment by zagy** [comment]
Well, actually we don't talk about setuptools. I assume you get an error when just calling `./batou`?

In this case I'd also assume `virtualenv --python=python2.7 foo` doesn't work anymore. This again is nothing we can fix from batou.

**Comment by icemac** [comment]
The error already happens when calling `./batou`.
And you are right `virtualenv --python=python2.7 foo` does not work any more even though `virtualenv` is the one from Python 2.7.

The thing that works is `virtualenv --no-download foo` as it installs the `setuptools` version bundled inside `virtualenv`.

**Comment by icemac** [comment]
I'll have a look into this issue right now.

**Comment by zagy** [comment]
Released batou 1.12.2
