### ISSUE TITLE
failures loading components are missing position information

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#261]
In situations like this we are missing the positioning information. Full tracebacks might not be necessary but the last entry would be helpful.

```
ERROR: Failed loading component file
      File: /Users/ctheune/Code/fc.directory.deployment/components/nginx/component.py
 Exception: __init__() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by icemac** [comment]
I've also seen this kind of errors when migrating from batou 2.3b2 to 2.3b3.
The error message does not tell that it is an `Attribute` instantiation which causes this problem.
Maybe we could solve it by accepting arbitrary positional arguments but raising an exception with an what to do inside `__init__` if `*args` is not empty.

**Comment by elikoga** [comment]
Alternatively to editing `Attribute`, I'd enrich this catch block with traceback and positional information:
https://github.com/flyingcircusio/batou/blob/e6dabac30733f5a90205b9eb994e34aab21493a0/src/batou/environment.py#L217-L220
