### ISSUE TITLE
batou.lib.git.Clone() might delete component folder when target is left empty

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#27]
When not explicit giving a target for the Clone-component, it might happen that the folder below deployment/work/ gets deleted. 

The default for `target` is set to the workdir of the component (`self.map('.')`). Later on it's checked whether there is a folder .git below this structure. If this folder is not found, it happen that `Clone()` is calling `ensure_path_nonexistent(self.target)` which results in deletion of this directory.

### Environment: 
```ini
[environment]
connect_method = local

[host:localhost]
components =
        testclone1
        testclone2
```

### Dummy component

```python
import batou.component
import batou.lib.git


class Testclone1(batou.component.Component):

    def configure(self):
        self += batou.lib.git.Clone(
            'git@github.com:flyingcircusio/batou.git',
            branch='master')


class Testclone2(batou.component.Component):

    def configure(self):
        self += batou.lib.git.Clone(
            'git@github.com:flyingcircusio/batou.git',
            target='checkout',
            branch='master')

```

**Comment by ctheune** [comment]
Ok, to clean up terminology: we're talking about the components' "workdir". So the workdir may be deleted (temporarily) if you want it to be a clone of a repository and it doesn't have a .git. So this likely happens during the first time.

We can't clone in a non-empty directory. So either, you want batou to clone something there or you can have something in that directory. If not .git exists, then you can only clone when it's really empty. As batou is intended to be a utility to automatically enforce policy then this is a "be careful what you wish for". I can't see a useful safety belt here without making the user perform a manual dance on the target ... I'm voting to not change this, unless I get better input for why we need to change this.

**Comment by frlan** [comment]
@ctheune  The deployment fails if `target` is not set as it's trying to git clone into a non-existing directory. Using `git.Clone()` as in `Testclone1()` is just not working.

**Comment by ctheune** [comment]
Ok, so that's a completely different picture than what I read from the previous statement. Alright. I think I can adjust for that.

**Comment by ctheune** [comment]
So I guess I'll just _clear out_ the target directory instead of deleting it so it becomes an empty directory and then we can clone into it. Will get to that on Friday, I guess.
