### ISSUE TITLE
Extend batou.lib.git.Clone() to stop on unclean checkout target

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#298]
Currently `batou.lib.git.Clone()` does a Clone also in case of the git status is detecting some changed code inside the checkout target folder:

```python
    def has_changes(self):
        with self.chdir(self.target):
            stdout, stderr = self.cmd("git status --porcelain")
        return bool(stdout.strip())
````

and from `verify()`

```python
            if self.has_changes():
                output.annotate(
                    "Git clone at {} is dirty, going to lose changes.".format(
                        self.target
                    ),
                    red=True,
                )
                raise UpdateNeeded()
```

I think we might should add an flag to prevent this and rather failing the deployment. 

Some applications like Wordpress are storing content created/manipulated by them inside the source folders all around the codebasis. It's not always 100% determinable where they will be. When proceeding with an unclean git status data/changes might get lost.

**Comment by ctheune** [comment]
"no_clobber" could be a good option name as it's in line with unix philosophy. thanks @elikoga
