### ISSUE TITLE
Misleading error message: Attribute override found both in environment and secrets

### ISSUE THREAD

**Issue by nichmoe** [flyingcircusio/batou#331]
Version: 2.4.b5

The following error message is also produced if the attribute is present multiple times in the secrets but not in the environment. In this case the error message is factually wrong.

```
ERROR: Attribute override found both in environment and secrets
      Component: component
      Attribute: some_attribute
```

**Comment by elikoga** [comment]
Ist das Erwartete Verhalten, dass die Sektionen gemerged werden? Ähnlich wie bei den normalen overrides?

Siehe 

environment.py:

```python
            self.overrides.setdefault(root_name, {})
            self.overrides[root_name].update(config[section])
```

**Comment by elikoga** [comment]
Already merged in https://github.com/flyingcircusio/batou//commit/1372ae3cc0ff074e2abd13be3b931d3659a667a8
