### ISSUE TITLE
supervisor systemd unit doesn't use Restart=always and customizing systemd parameters seems broken

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#339]

**Comment by ctheune** [comment]
Relevant code places:

* using supervisord will trigger a Service component (supervisord.py:227)
* the Service component is "Abstract" as it needs a platform-specific hookup with init.d or systemd
* batou_ext has the nixos platform integration: (https://github.com/flyingcircusio/batou_ext/blob/master/src/batou_ext/nix.py#L182)
* however, there is no way to pass in customizations AFAICT and *IMHO* restart=always should be the default anyways

**Comment by ctheune** [comment]
@sweh is interested in the fix for this

**Comment by elikoga** [comment]
customizing systemd service parameters works, as far as I can replicate; here is an example file that creates and modifies a systemd service with unit file modifications:

```
from batou.component import Component
from batou.lib.file import File
from batou.lib.service import Service
import batou_ext.nix


class Tick(Component):
    def configure(self):
        self += File(
            "tick.sh",
            mode="rwxr-xr-x",
            content="""\
#!/bin/bash
while true; do
  date
  sleep 1
done
""",
        )
        self += Service("tick.sh", systemd=dict(
                Restart="always"
                Type="simple",
                ))
```

I will be setting Restart=always in a PR on batou_ext in a bit

**Comment by elikoga** [comment]
All uses of `Service(...)` I can find already set systemd=dict(...Restart='always'...)

Setting this as default and mentioning it in the docs should be reasonable

**Comment by elikoga** [comment]
Not sure what is meant by `customizing systemd parameters seems broken`

**Comment by elikoga** [comment]
@sweh could you elaborate what's going wrong? Or is the code snippet enough to explain systemd behaviour on the fc nixos platform
