### ISSUE TITLE
lib.File: add header template variable to environment

### ISSUE THREAD

**Issue by elikoga** [flyingcircusio/batou#356]
When generating files using `batou.lib.File`, it is useful to add a header to the file that indicates that the file is generated by batou and should not be edited manually. This is currently done by hand by writing the header into the file in the deployment repository. This should be automated by adding a `batou_generated_header` template variable to the template rendering environment, which can be used in the template to add the header to the file.

**Comment by stevleibelt** [comment]
@elikoga could you be so kind and add a link to "the discussion in applications on 02.03", if the discussion is public and "linkable"?

Best regards,
Stev
