### ISSUE TITLE
age-based encryption - need general command to update/reencrypt all secrets in all environments

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#398]
Adding a new person requires to re-encrypt the files. AFAIK currently one has to edit (and change!) all environments to fetch updates for the keys end reencrypt and do that manually for all environments.

I think we need something like a `secrets update` command.

Also, there seems to be a bug with the existing add/remove commands (which are gpg-specific) and the "environments" parameter seems broken.

**Comment by elikoga** [comment]
I think this can fit in 2.4.1
