### ISSUE TITLE
AppEnv cleanup too early?

### ISSUE THREAD

**Issue by sweh** [flyingcircusio/batou#62]
Cleaning up old appenvs is too early in my setup: Between AppEnvs configure (with cleanup) and the restart of my instances, errors like `ValueError: Missing template asset: pkg:templates/login.pt (/srv/user/deployment/work/portal/.appenv/898d917c87d9d9207360432cbf5cfed35ef2bcc087b3d8a459d26bcfcfab7705/lib/python3.6/site-packages/pkg/templates/login.pt)` or `Can't connect to server (Could not find a suitable TLS CA certificate bundle, invalid path: /srv/user/deployment/work/portal/.appenv/344b3ce7e373d2de5cc51a45e018e57243fe8597139d85c1471509f9081fdf9e/lib/python3.6/site-packages/certifi/cacert.pem)` might occur.

We should either find a solution that the resolved path uses the `current` link instead of the hash (preferred) or kind of mark an appenv as deleted and remove it some time later.

**Comment by ctheune** [comment]
Ah this, is done AFAICT.
