### ISSUE TITLE
./batou appenv-update-lockfile causes wrong requirements.lock in combination with batou_ext

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#67]
Having a minimal requirements.txt at the project:

```
batou==2.0b12
batou_ext @ https://github.com/flyingcircusio/batou_ext/archive/5b3a8de035d8b68e98aa10483568dd5fa524a149.zip#sha256=972260e6186ee4211f63f18d598db697169c2e1151189fe88d45b85e1028b2a2
```
After running 
```
./batou appenv-update-lockfile                  
Updating lockfile
Creating venv ...
Ensuring pip ...
Installing packages ...
```

the created requirements.lock is not reflecting the batou_ext-dependency correctly

```
% cat requirements.lock 
apipkg==1.5
batou==2.0b12
batou-ext==0.1.dev0
certifi==2020.4.5.1
chardet==3.0.4
execnet==1.7.1
idna==2.9
Jinja2==2.11.2
MarkupSafe==1.1.1
py==1.8.1
pyaml==20.4.0
PyYAML==5.3.1
requests==2.23.0
six==1.15.0
urllib3==1.25.9
```

**Comment by jugmac00** [comment]
Yep - just experienced the same problem.

Manually copy/pasting the batou_ext version into the lockfile is a current workaround.

**Comment by ctheune** [comment]
This has been fixed with a sufficiently new appenv version (https://github.com/flyingcircusio/appenv/commit/ab919b1f6e5be6a7ed3d47a1fe2daeb133dc3c87#diff-80c588363ebc8620a3b639f4d5c5588a64e8ca80a68ac17d9dce87cc63ea3f7e)
