### ISSUE TITLE
check_supervisor fails with `module 'nagiosplugin' has no attribute 'Measure'`

### ISSUE THREAD

**Issue by zagy** [flyingcircusio/batou#80]
```
vagrant@nixos ~/.../work/supervisor $ ./check_supervisor
Traceback (most recent call last):
  File "/home/vagrant/deployment/work/supervisor/bin/py", line 30, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "./check_supervisor", line 14, in <module>
    class BucketMeasure(nagiosplugin.Measure):
AttributeError: module 'nagiosplugin' has no attribute 'Measure'
```

Indeed nagiosplug doesn't import that in `__init__.py`

**Comment by ctheune** [comment]
And I think we can actually call this in the tests because they do run the supervisor component

**Comment by gforcada** [comment]
I'm seeing that as well on our servers, is there any workaround for the time being? :thinking:

**Comment by ctheune** [comment]
Sorry, not yet. I spent time on batou last week but got stuck on having to move away from Travis ...

**Comment by ctheune** [comment]
I think I have a fix on master available - I had to rewrite the script because the nagiosplugin library IMHO became too complicated for this simple task and we broke API compatibility anyway with the move to Python 3.

I haven't added tests for this yet, but will do to avoid future breakage.

**Comment by ctheune** [comment]
fixed
