### ISSUE TITLE
get started with batou. readme instructions: requirements.txt missing

### ISSUE THREAD

**Issue by ksuess** [flyingcircusio/batou#82]
Hi flying circus

Syslab suggested to use batou for https://www.zhkath.ch . Glad they did.

So, now, for a new project:
Starting with instructions of https://github.com/flyingcircusio/batou/blob/master/README.md

A requirements.txt with
`git+git://github.com/flyingcircusio/batou_ext.git@255abd80495e018c07b73d3a20bbf4319a2a534d#egg=batou_ext`
helps to run without fail. Maybe you want to text a little bit the readme.

**Comment by ctheune** [comment]
Thanks - sounds like you like it! 

I'll compare the starting instructions in the README with the detailed logs. Can you send me what fails for you when you don't add batou_ext?

**Comment by ksuess** [comment]
Hi, thanks for caring.

What I did to start from scratch:
```
mkdir myproject
cd myproject
curl https://raw.githubusercontent.com/flyingcircusio/batou/master/appenv.py -o batou
chmod +x batou
./batou
```

```
Running unclean installation from requirements.txt
Creating venv ...
Ensuring pip ...
Ensuring unclean install ...
.batou/unclean/bin/python -m pip install -r requirements.txt --upgrade returned with exit code 1
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Traceback (most recent call last):
  File "./batou", line 40, in cmd
    return subprocess.check_output([c], **kwargs)
  File "/Users/ksuess/.pyenv/versions/3.7.8/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/ksuess/.pyenv/versions/3.7.8/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['.batou/unclean/bin/python -m pip install -r requirements.txt --upgrade']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./batou", line 312, in <module>
    main()
  File "./batou", line 308, in main
    meta_args.func(argv, meta_args)
  File "./batou", line 200, in run
    env_dir = _prepare(meta_args)
  File "./batou", line 151, in _prepare
    cmd('{env_dir}/bin/python -m pip install -r requirements.txt --upgrade'.format(env_dir=env_dir))
  File "./batou", line 44, in cmd
    raise ValueError(e.output.decode('ascii'))
ValueError: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

```

**Comment by ctheune** [comment]
Ah, right. OK, I understand that. I'll update the docs ... :)

**Comment by ctheune** [comment]
Just to let you know about the better way to do that:

$ curl -sL https://raw.githubusercontent.com/flyingcircusio/batou/master/src/bootstrap | sh

**Comment by ctheune** [comment]
The RTD-based docs are already up to date: https://batou.readthedocs.io/en/stable/user/install.html#starting-a-new-batou-project

I'll update the README soon.

**Comment by ksuess** [comment]
I think this is meant:
https://raw.githubusercontent.com/flyingcircusio/batou/master/bootstrap

`curl -sL  https://raw.githubusercontent.com/flyingcircusio/batou/master/bootstrap | sh`
works well, bootstrap is done.

https://batou.readthedocs.io/en/stable/user/install.html#starting-a-new-batou-project
mentions a file that does not exist.

Anyway, I'm quite thrilled. On the way setting up a Plone Volto project with batou for deployment and pm2 for process management.

**Comment by ctheune** [comment]
Oh, good catch, thanks!

Really happy that you like it so far!

What's pm2?

**Comment by ksuess** [comment]
Amazing Volto team inspired me: https://docs.voltocms.com/deploying/pm2/
PM2 Quickstart: https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/
With pm2 all processes can be managed like with supervisor. What comes in handy is a watch option to rebuild and reload the app on a batou run that updates the app source.

**Comment by ctheune** [comment]
just double checked: readme and RTD reference the proper bootstrap mechanism now.
