### ISSUE TITLE
Plone add-on github. ssh_config

### ISSUE THREAD

**Issue by ksuess** [flyingcircusio/batou#83]
Goal
Use Plone add-on _xyz_ from github.

Github repository xyz got a contributor `iamyourcontributor`. His key is added to secrets of environment  (github_ssh_key) 
The key is picked up and deployed by component _common_.

```
class Common(Component):

    github_ssh_key = None

    def configure(self):
        self.provide('common', self)
        self += SSH(key=self.github_ssh_key)


class SSH(Component):

    scan_hosts = ''

    def configure(self):
        self.scan_hosts = self.scan_hosts.split()
        for host in self.scan_hosts:
            self += batou_ext.ssh.ScanHost(host)

        self += batou.lib.file.File('~/.ssh', ensure='directory', mode=0o700)
        self += batou.lib.file.File('~/.ssh/config', source='ssh_config')
        self += batou.lib.file.File(
            '~/.ssh/github', content=self.key, mode=0o600)

```

So on remote machine the key is placed on <>/work/_/home/zhkath/.ssh/githüb

**What is necessary to get this private key to be available on buildout clone/pull?**

```
 mr.developer: Cloned 'xyz with git from 'https://github.com/wonderwoman/xyz.git'.
     mr.developer: git cloning of 'xyz' failed.
     mr.developer: fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by icemac** [comment]
@ksuess Did you try to use an SSH GitHub URL (instead of HTTPS)? This should be the kind to be used together with an SSH key.

**Comment by ksuess** [comment]
@icemac Yes, I changed the address to git@github.com:... it's definitely necessary for cloning via ssh.

Still not found an elegant solution for making GitHub contributors ssh key present for cloning. I copied it manually from work/_/home/service_user/.ssh/ to ~/.ssh and modified ~/.ssh/config (home of environments service_user)

**Comment by ctheune** [comment]
Ah, you have developer sandbox mapping enabled. The work/_/ is not intended to be used for real hosts ... What's the reason you enabled it?

**Comment by ksuess** [comment]
Wow, thank you for your immediate response, @ctheune . Do I get you right that batou should overwrite service_user ~/.ssh/config and place the key in ~/.ssh?

**Comment by ctheune** [comment]
Usually you might not have to override ~/.ssh/config but it's definitely an option. And yes: as batou is a system to automate deployments, you want (and need it) to modify the target system in "appropriate" places, so putting it in a sandbox is really just intended to help with local deployments during development - a very limited scenario actually, not the default.

**Comment by ctheune** [comment]
I guess this is resolved. Feel free to open it again if I'm wrong.
