### ISSUE TITLE
output.annotate not working with debug=True

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#85]
For testing reasons I've added to the verify-method of lib.file.SyncDirectory 

```
    def verify(self):
        stdout, stderr = self.cmd('rsync {} {}{}/ {}'.format(
            self.verify_opts, self.exclude_arg, self.source, self.path))
…
        output.annotate('debug not activated')
        output.annotate('debug activated', debug=True)
```

two custom output.annotate-calls. My expectation was, that I can see both messages when running batou with --debung like this

`% ./batou --debug deploy -P vagrant`

When running, I was only seeing the non-debug output

```
…snip…
default: message: ('batou-output', 'line', ('debug not activated',), {})
debug not activated
default: message: ('batou-result', None)
…snap…
```

**Comment by ctheune** [comment]
I fixed that while working on the container support improvements. Will be in 2.3b3 or so.
