### ISSUE TITLE
NetLoc objects not sortable with Python3

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou#88]
When trying to sort a list of NetLoc objects I'm getting

`'<' not supported between instances of 'NetLoc' and 'NetLoc'`

As I workaround I've converted it to str 

`self.servers = sorted(self.require('backend'), key=lambda c: str(c.address.connect))`

**Comment by ctheune** [comment]
This is just to get a stable sorting, right?

**Comment by frlan** [comment]
Yes.
