### ISSUE TITLE
File diff and sensitive values improvements

### ISSUE THREAD

**Issue by zagy** [flyingcircusio/batou#91]
There is currently a way to mark entire files to contain sensitive data. Those are not diff'ed then. This could be improved when you could pass a list of sensitive *values* to `File()` which could be masked in the output.

**Comment by ctheune** [comment]
Ok, a way to start this that I suggest:

* check whether any secret values are in the old or new file
* do not provide any diff if that's the case
* but let the diff go on disk (as we do with long disks already)

**Comment by zagy** [comment]
Another variant would be to just replace() all secrets with some static text

**Comment by ctheune** [comment]
We discussed this, however, the diff will contain _old_ secrets that we can't identify any longer ... :/

**Comment by ctheune** [comment]
And trying to match secrets within the diff and then figure out which corresponding part of the diff likely also has a secret is a bit over the top for now.

**Comment by zagy** [comment]
Ah, right. Unknown secrets are bad, indeed :)
